### ISSUE TITLE
Add Import shows "Sorry, please wait a..."

### ISSUE THREAD

**Issue by ghost** [cybertim/vscode-gengetset#22] opened 2016-07-13 20:48 UTC
When I run the command "Add Import", I get a warning saying: "Sorry, please wait a few seconds longer until the export cache has been build.". This won't go away even when I wait several minutes.

This error occurs when I am trying to run the command in an angular cli application.
Works fine if a have an empty project with only a couple of ts-files.

**Comment by cybertim** [comment] 2016-07-14 08:51
Is it possible to supply some details or an archive/gist/git with a project having this issue?
I can't seem to reproduce this, but some people keep complaining about it.

**Comment by mattwilson1024** [comment] 2016-07-14 10:37
I'm also having this issue with a project created using the [angular-cli](https://github.com/angular/angular-cli).

**Comment by cybertim** [comment] 2016-07-14 16:41
![screen shot 2016-07-14 at 18 39 27](https://cloud.githubusercontent.com/assets/5379564/16847640/5a4a69a0-49f2-11e6-97d4-bce971384c6f.png)

Add Import does work when I generated a test project with the angular-cli, but there are a lot of things that are getting indexed (1010 in my example) so maybe on a slow computer this can take a while?

**Comment by ghost** [comment] 2016-07-14 17:47
I have no problem on my Macbook Air. Took 2-3 seconds and 875 items were indexed. But on my PC which are more powerful than my mac, nothing seems to get indexed. I've had my project open for 45 minutes and the index-icon still show reloading icon.

![image](https://cloud.githubusercontent.com/assets/6557961/16849689/ebb0be68-49fb-11e6-839e-66850522ea95.png)

**Comment by cybertim** [comment] 2016-07-15 06:55
Ok, then the main question would be: is on the macbook the `add imports` etc working?

If so, the issue is probably related to the indexing on windows for some reason.
This weekend I will coincidently complete my PC build so I can test the code on windows as well.

**Comment by jslocalhost** [comment] 2016-07-29 14:51
getting this same message and no import export is made. Is it fixed somewhere?

**Comment by cybertim** [comment] 2016-08-05 11:11
If you/someone experience this issue (still) please list your version of the extension and what OS/Platform you're on, and if possible:
Did you open a project? Or start one from scratch?
Did you use a specific framework/generated boilerplate?

**Comment by ghost** [comment] 2016-08-08 21:15
Extension version: 0.3.3
OS: Windows 8.1

I get this issue both when starting a new project using the angular cli for angular 2 and Ionic cli for Ionic 2. Got no problem starting a new typescript project from scratch.

**Comment by tsvetan-ganev** [comment] 2016-08-14 17:07
I also have this issue when working on a Angular 2 CLI project.

Version: 0.3.3
OS: Windows 10

**Comment by marcus-robinson** [comment] 2016-08-18 21:35
I'm seeing this issue too. 

Version of the extension 
**0.3.3**
OS: 
**Windows 8.1 enterprise 64 bit**
Did you open a project? Or start one from scratch? 
**Opened an existing project**
Did you use a specific framework/generated boilerplate? 
**No - this is a pure typescript project**

**Package.json**
`{
  "name": "card-game",
  "version": "1.0.0",
  "description": "",
  "main": "./dist/main.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "gulp": "^3.9.1",
    "gulp-typescript": "^2.13.6",
    "immutable": "^3.8.1",
    "jasmine-core": "2.4.1",
    "lodash": "^4.12.0"
  },
  "dependencies": {
    "merge2": "^1.0.2",
    "signals": "^1.0.0"
  }
}`

**tsconfig.json**
`{
  "compilerOptions": {
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es5",
    "module": "commonjs",
    "declaration": true,
    "outDir": "dist",
    "noImplicitAny": true
  },
  "filesGlob": [
    "src/**/*.ts",
    "typings/index.d.ts",
    "!node_modules/**/*"
  ],
  "exclude": [
    "node_modules"
  ],
  "compileOnSave": false,
  "buildOnSave": false,
  "atom": {
    "rewriteTsconfig": false
  }
}`

**Comment by cybertim** [comment] 2016-08-21 08:58
Should be fixed in version 0.3.4

Issue was related to windows paths being analyzed as `/c:/` instead of `c:/`

**Closed as completed by cybertim** 2016-08-21 08:58 UTC
Labels: bug, help wanted

**Comment by ghost** [comment] 2016-08-23 07:03
Works like a charm. Great work!
